server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie

spring:
  profiles:
    active: local
  common:
    datasource:
      driver-class-name: cubrid.jdbc.driver.CUBRIDDriver
      jdbc-url: "jdbc:cubrid:127.0.0.1:30000:demodb:survey::"
      username: survey
      password:

mybatis:
  type-aliases-package: com.ultari

logging.level.com.ultari.additional: info

#계정 암호화용 (현재 사용 X)
common:
  account:
    encrypt:
      driver: kr.co.ultari.cryptor.seed.Codec
      method: encrypt
      use: false
      use-wrapping-base64: true
    decrypt:
      method: decrypt
  api:
    ip: 127.0.0.1
    port: 1234
    timeout: 3
    survey-noti-domain: http://127.0.0.1:8080/
  organization:
    top-dept-id: ultari1

#admin 조직도 동기화에 사용
#주석 처리 요망
rest-template:
  factory:
    read-timeout: 5000
    connect-timeout: 3000
  http-client:
    max-conn-total: 100
    max-conn-per-route: 5
  org-sync-url: http://127.0.0.1:18002/O/?M=orgSync


